# Generated by Django 3.1.5 on 2021-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRealtime',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=8)),
                ('message', models.CharField(max_length=2048)),
            ],
        ),
    ]
