# Generated by Django 3.1.5 on 2021-01-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210128_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationRealtime',
            new_name='Realtime',
        ),
    ]
