# Generated by Django 3.1.5 on 2021-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20210128_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('variables', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RemoveField(
            model_name='realtime',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Realtime',
        ),
    ]
