# Generated by Django 3.1.5 on 2021-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20210205_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Event',
        ),
    ]
