# Generated by Django 3.1.3 on 2021-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRealtime',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(max_length=8)),
                ('message', models.CharField(max_length=2048)),
            ],
        ),
    ]
